version: '3.7'
services:
  grafana:
    image: grafana/grafana-enterprise:8.4.7
    ports:
      - '3000:3000'
    volumes:
      - ./:/var/lib/grafana/plugins/grafana-astradb-datasource
      - ./provisioning/config/license:/etc/license
      - ./provisioning/provisioning:/etc/grafana/provisioning
    environment:
      - TERM=linux
      - GF_LOG_LEVEL=debug
      - GF_DATAPROXY_LOGGING=true
      - GF_DEFAULT_APP_MODE=development
      - GF_ENTERPRISE_LICENSE_PATH=/etc/license/license.jwt